import { downloadImage } from '../services/imageGeneration.js';

/**
 * Export Brief — decoration summary with TXT download, PDF export,
 * and (when available) generated image download.
 *
 * Props:
 *   state       — decor state object
 *   hall        — { name, emoji } | null
 *   imageUrl    — generated image data-URL | null
 *   onBack      — fn
 */

const SECTIONS = [
  { key: 'primary_colors',    label: 'Primary Colours' },
  { key: 'types_of_flowers',  label: 'Flowers' },
  { key: 'decor_lights',      label: 'Decorative Lighting' },
  { key: 'chandeliers',       label: 'Chandeliers' },
  { key: 'props',             label: 'Props' },
  { key: 'selfie_booth_decor', label: 'Selfie Booth' },
  { key: 'hall_decor',        label: 'Hall Decoration' },
];

const ENTRANCE_KEYS = [
  { key: 'foyer',                  label: 'Foyer' },
  { key: 'garlands',               label: 'Garlands' },
  { key: 'name_board',             label: 'Name Board' },
  { key: 'top_decor_at_entrance',  label: 'Top Decor at Entrance' },
];

// ── Plain-text brief builder ──────────────────────────────────────

function buildBriefText(state, hall) {
  const hr = '─'.repeat(50);
  const lines = [
    'MAYA — SOUTH INDIAN WEDDING DECORATION BRIEF',
    '='.repeat(50),
    '',
  ];

  if (hall?.name) {
    lines.push(`Hall : ${hall.name}`);
    lines.push('');
  }

  SECTIONS.forEach(({ key, label }) => {
    const items = state[key] || [];
    if (!items.length) return;
    lines.push(`${label}:`);
    items.forEach(v => lines.push(`  • ${v}`));
    lines.push('');
  });

  const ent = state.entrance_decor;
  if (ent) {
    const hasAny = ENTRANCE_KEYS.some(({ key }) => ent[key]?.length);
    if (hasAny) {
      lines.push('Entrance Decoration:');
      ENTRANCE_KEYS.forEach(({ key, label }) => {
        (ent[key] || []).forEach(v => lines.push(`  • ${label}: ${v}`));
      });
      lines.push('');
    }
  }

  if (state.backdrop_decor?.enabled && state.backdrop_decor.types?.length) {
    lines.push('Stage Backdrop:');
    state.backdrop_decor.types.forEach(t => lines.push(`  • ${t}`));
    lines.push('');
  }

  lines.push(hr);
  lines.push('Generated by Maya AI Wedding Planner');
  return lines.join('\n');
}

// ── Component ─────────────────────────────────────────────────────

export default function ExportBrief({ state, hall, imageUrl, onBack }) {
  if (!state) return null;

  const hallSlug = (hall?.name || 'visualization').toLowerCase().replace(/\s+/g, '-');

  const handleDownloadTxt = () => {
    const text = buildBriefText(state, hall);
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = 'maya-decoration-brief.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleExportPdf = () => window.print();

  return (
    <div className="export">
      <div className="export__header">
        <button className="export__back" onClick={onBack}>← Back</button>
      </div>

      <div className="export__card" id="export-printable">
        <h1 className="export__title">Decoration Brief</h1>
        <p className="export__subtitle">
          South Indian Wedding — Hall Decoration Plan
          {hall?.name ? ` · ${hall.emoji ?? ''} ${hall.name}` : ''}
        </p>

        {/* Generated image preview + download */}
        {imageUrl && (
          <div className="export__image-section no-print-hide">
            <img
              src={imageUrl}
              alt={hall?.name ? `Decorated ${hall.name}` : 'Decorated Hall'}
              className="export__image-preview"
            />
            <div className="export__image-actions">
              <button
                className="btn-secondary"
                onClick={() => downloadImage(imageUrl, 'png', `maya-${hallSlug}`)}
              >
                ↓ Download PNG
              </button>
              <button
                className="btn-secondary"
                onClick={() => downloadImage(imageUrl, 'jpg', `maya-${hallSlug}`)}
              >
                ↓ Download JPG
              </button>
            </div>
          </div>
        )}

        {/* Decor sections */}
        {SECTIONS.map(({ key, label }) => {
          const items = state[key] || [];
          if (!items.length) return null;
          return (
            <div key={key} className="export__section">
              <h3 className="export__section-title">{label}</h3>
              <div className="export__items">
                {items.map((item, i) => (
                  <span key={i} className="export__item">{item}</span>
                ))}
              </div>
            </div>
          );
        })}

        {/* Entrance */}
        {state.entrance_decor && ENTRANCE_KEYS.some(({ key }) => state.entrance_decor[key]?.length) && (
          <>
            <div className="export__section">
              <h3 className="export__section-title">Entrance Decoration</h3>
            </div>
            {ENTRANCE_KEYS.map(({ key, label }) => {
              const items = state.entrance_decor?.[key] || [];
              if (!items.length) return null;
              return (
                <div key={key} className="export__section" style={{ paddingLeft: '1rem' }}>
                  <h3 className="export__section-title" style={{ fontSize: '0.7rem' }}>{label}</h3>
                  <div className="export__items">
                    {items.map((item, i) => (
                      <span key={i} className="export__item">{item}</span>
                    ))}
                  </div>
                </div>
              );
            })}
          </>
        )}

        {/* Backdrop */}
        {state.backdrop_decor?.enabled && (state.backdrop_decor.types || []).length > 0 && (
          <div className="export__section">
            <h3 className="export__section-title">Stage Backdrop</h3>
            <div className="export__items">
              {state.backdrop_decor.types.map((t, i) => (
                <span key={i} className="export__item">{t}</span>
              ))}
            </div>
          </div>
        )}

        {/* Action row */}
        <div className="export__actions no-print">
          <button className="btn-secondary" onClick={handleDownloadTxt}>
            ↓ Download TXT
          </button>
          <button className="btn-secondary" onClick={handleExportPdf}>
            ↓ Export PDF
          </button>
        </div>
      </div>
    </div>
  );
}
